name: main-workflow
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  test:
    uses: ./.github/workflows/01-analyze-test.yml

  # TODO: implement conventional release
  # conventional-release:
  #    needs:
  #      - test-analyze
  #    uses: ./.github/workflows/02-conventional-release.yml
  #    secrets: inherit

  parse-screenshot:
    uses: ./.github/workflows/01-parse-screenshot.yml
    with:
      # Set to empty string to always take screenshots
     #  screenshot-text: "SCREENSHOT"
      screenshot-text: ""

  build-android:
    # set if false to disable android branch of build
    # if: ${{ needs.conventional-release.outputs.new_release_published == 'true' }}
    needs:
    - test
    - parse-screenshot
    #    needs:
    #      - conventional-release
    #      - parse-screenshot
    uses: ./.github/workflows/03-build-android.yml
    with:
      screenshot: ${{ needs.parse-screenshot.outputs.contains_screenshot }}
      apk: "true"
    secrets: inherit

#  build-ios:
#    # set if false to disable iOS branch of build
##    if: ${{ needs.conventional-release.outputs.new_release_published == 'true' }}
#    needs:
#      - test
##      - conventional-release
##      - parse-screenshot
#    uses: ./.github/workflows/03-build-ios.yml
#    with:
##       screenshot: ${{ needs.parse-screenshot.outputs.contains_screenshot }}
#      ipa: "true"
#    secrets: inherit

  integration-screenshot-android:
    if: ${{ needs.parse-screenshot.outputs.contains_screenshot == 'true' }}
    needs:
      - parse-screenshot
      - build-android
    uses: ./.github/workflows/10-take-screenshot-android.yml
    with:
      api_level: 30
      model: "['pixel_6']"

#   upload-android:
#     if: ${{ needs.parse-screenshot.outputs.contains_screenshot == 'false' }}
#     needs:
#       - build-android
#       - conventional-release
#     uses: ./.github/workflows/04-upload-android.yml
#     with:
#       new_release: ${{ needs.conventional-release.outputs.new_release }}
#       new_release_notes: ${{ needs.conventional-release.outputs.new_release_notes }}
#     with:
#       new_release: "v1.0.1"
#       new_release_notes: "test release notes"
#     secrets: inherit

#  upload-ios:
##     if: ${{ needs.parse-screenshot.outputs.contains_screenshot == 'false' }}
#    needs:
##       - parse-screenshot
#      - build-ios
##       - conventional-release
#    uses: ./.github/workflows/04-upload-ios.yml
#    with:
#      new_release: "v1.0.1"
#      new_release_notes: "test release notes"
#    secrets: inherit
