name: main-workflow
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  test:
    uses: ./.github/workflows/01-analyze-test.yml

  # TODO: implement conventional release
  # conventional-release:
  #    needs:
  #      - test-analyze
  #    uses: ./.github/workflows/02-conventional-release.yml
  #    secrets: inherit

  # TODO: implement automatic screenshots
  # parse-screenshot:
  #    uses: ./.github/workflows/11-parse-screenshot.yml
  #    with:
  #      # Set to empty string to always take screenshots
  #      screenshot-text: "SCREENSHOT"

  build-android:
    # set if false to disable android branch of build
#     if: ${{ needs.conventional-release.outputs.new_release_published == 'true' }}
    needs:
      - test
#    needs:
#      - conventional-release
#      - parse-screenshot
    uses: ./.github/workflows/03-build-android.yml
    with:
      # screenshot: ${{ needs.parse-screenshot.outputs.contains_screenshot }}
      apk: "true"
    secrets: inherit

  build-ios:
    # set if false to disable iOS branch of build
#    if: ${{ needs.conventional-release.outputs.new_release_published == 'true' }}
    needs:
      - test
#      - conventional-release
#      - parse-screenshot
    uses: ./.github/workflows/03-build-ios.yml
    with:
#       screenshot: ${{ needs.parse-screenshot.outputs.contains_screenshot }}
      ipa: "true"
    secrets: inherit

  upload-android:
#     if: ${{ needs.parse-screenshot.outputs.contains_screenshot == 'false' }}
    needs:
      - build-android
#       - conventional-release
    uses: ./.github/workflows/04-upload-android.yml
#     with:
#       new_release: ${{ needs.conventional-release.outputs.new_release }}
#       new_release_notes: ${{ needs.conventional-release.outputs.new_release_notes }}
    with:
      new_release: "v1.0.1"
      new_release_notes: "test release notes"
    secrets: inherit
